name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install_dependencies
        run: npm i
        working-directory: ./frontend
      - name: build_Angular
        run: npm run build
        working-directory: ./frontend
      - name: deploy_Artifact
        id: build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist/frontend/browser


  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4